language: ruby
rvm:
  - 2.0.0-p598
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.4
  - 2.2.0
  - 2.2.1
  - 2.2.2
before_install:
- gem install bundler
- export TZ=Australia/Canberra
deploy:
  provider: rubygems
  api_key:
    secure: FZVmAZ6QMTUCZU4Iogf3J+                                                                                                             DgVyqZMi353GaG1wecIejOgsZd5mcZu7j0AS2OFcU9gvoq28DG3v0aM70KoFqGIgcxPoP2Y84B6USK3rpVxGxudcj6yXuVLqvLWv2l47oUTVU5Z71GL42m6UchYub23eVkZoyVTuzKUzxQ3P9nMNg=
  on:
    tags: true
